// Capture process observations, not engineering verdicts or execution permission.
import { spawn } from "node:child_process"
import { createHash, randomUUID } from "node:crypto"
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, statSync, writeFileSync, writeSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

const HELP = `evidence: retain actual command execution without a ledger

run <new-directory> [--cwd <directory>] [--input <file>]... -- <command> [argument]...
inspect <directory>

run executes the literal argument vector with normal process permissions. For shell syntax,
name the shell explicitly. Existing capture directories are never overwritten.
stdout.log and stderr.log retain bytes as they arrive; start.json records the invocation.
receipt.json is written only after the child and its output streams close. Selected input
files are copied before launch; this does not claim they are the process's only inputs.
run verifies the retained bytes and returns start, receipt, and stdout/stderr log paths.
Read those logs to interpret the result; no separate inspect is needed for a fresh capture.
run returns the child exit code, or nonzero for launch failure, interruption or capture error.

inspect checks retained file hashes for reused captures or recovery and returns the same facts.
It does not run a command or call an execution successful. With no closing receipt it
reports incomplete capture and returns nonzero; partial logs may still contain evidence.
An interrupted capture is inspectable but never a completed check, even with exit code 0.

This is not a sandbox, authentication service or process supervisor. Keep the command's
approval and shared-input ownership requirements. Stop jobs through their original runtime;
signals received here are forwarded to the direct child. Descendant job cleanup still needs
inspection. Logs and arguments may contain sensitive data; retain only authorized evidence.
`

interface FileFact { bytes: number; sha256: string }
interface InputFact extends FileFact { source: string; retained: string }
interface Start {
  schema: 1; id: string; startedAt: string; cwd: string; argv: string[]
  environment: { platform: string; arch: string; node: string }
  inputs: InputFact[]
}
interface Receipt {
  schema: 1; id: string; endedAt: string
  termination: "exited" | "signalled" | "interrupted" | "launch-failed" | "capture-failed"
  exitCode: number | null; signal: NodeJS.Signals | null; interrupt: NodeJS.Signals | null
  error: string | null; start: FileFact; stdout: FileFact; stderr: FileFact
}
function fact(bytes: Buffer): FileFact {
  return { bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") }
}
function save(path: string, value: unknown): FileFact {
  const bytes = Buffer.from(JSON.stringify(value, null, 2) + "\n")
  writeFileSync(path, bytes, { flag: "wx", mode: 0o600 })
  return fact(bytes)
}
function regular(path: string): Buffer {
  if (!statSync(path).isFile()) throw new Error(`not a regular file: ${path}`)
  return readFileSync(path)
}
function check(path: string, expected: FileFact): void {
  const actual = fact(regular(path))
  if (!expected || actual.bytes !== expected.bytes || actual.sha256 !== expected.sha256) throw new Error(`capture bytes changed: ${path}`)
}

export function inspect(directory: string): { start: Start; receipt: Receipt | null } {
  const startPath = join(directory, "start.json")
  const start = JSON.parse(regular(startPath).toString()) as Start
  if (start.schema !== 1 || typeof start.id !== "string" || !Array.isArray(start.argv) || !start.argv.length || !start.argv.every((v) => typeof v === "string") || typeof start.cwd !== "string" || !Array.isArray(start.inputs)) throw new Error("invalid capture start")
  for (const [index, input] of start.inputs.entries()) {
    // Retained paths are generated by the runner, never arbitrary paths supplied by JSON.
    if (input.retained !== `input-${index}`) throw new Error("invalid retained input path")
    check(join(directory, input.retained), input)
  }
  const receiptPath = join(directory, "receipt.json")
  if (!existsSync(receiptPath)) return { start, receipt: null }
  const receipt = JSON.parse(regular(receiptPath).toString()) as Receipt
  if (receipt.schema !== 1 || receipt.id !== start.id || !["exited", "signalled", "interrupted", "launch-failed", "capture-failed"].includes(receipt.termination)) throw new Error("invalid capture receipt")
  check(startPath, receipt.start)
  check(join(directory, "stdout.log"), receipt.stdout)
  check(join(directory, "stderr.log"), receipt.stderr)
  return { start, receipt }
}

async function run(args: readonly string[]): Promise<number> {
  const [output, ...rest] = args
  if (!output || output.startsWith("--")) throw new Error("run requires a new capture directory")
  const separator = rest.indexOf("--")
  if (separator < 0 || separator === rest.length - 1) throw new Error("run requires -- followed by command and arguments")
  let cwd = process.cwd(), specifiedCwd = false
  const inputs: string[] = []
  for (let i = 0; i < separator; i += 2) {
    const key = rest[i], value = rest[i + 1]
    if (i + 1 >= separator || !value) throw new Error(`missing value for ${key}`)
    if (key === "--cwd" && !specifiedCwd) { cwd = resolve(value); specifiedCwd = true }
    else if (key === "--input") inputs.push(value)
    else throw new Error(`invalid or repeated option: ${key}`)
  }
  if (!statSync(cwd).isDirectory()) throw new Error("--cwd must name a directory")
  const argv = rest.slice(separator + 1)
  if (!argv[0]) throw new Error("command must not be empty")
  const snapshots = inputs.map((path) => ({ source: resolve(cwd, path), bytes: regular(resolve(cwd, path)) }))
  const directory = resolve(output)
  mkdirSync(dirname(directory), { recursive: true })
  mkdirSync(directory, { mode: 0o700 })
  const start: Start = {
    schema: 1, id: randomUUID(), startedAt: new Date().toISOString(), cwd, argv,
    environment: { platform: process.platform, arch: process.arch, node: process.version },
    inputs: snapshots.map((input, i) => {
      const retained = `input-${i}`
      writeFileSync(join(directory, retained), input.bytes, { flag: "wx", mode: 0o600 })
      return { source: input.source, retained, ...fact(input.bytes) }
    }),
  }
  const startFact = save(join(directory, "start.json"), start)
  const stdout = { hash: createHash("sha256"), bytes: 0 }, stderr = { hash: createHash("sha256"), bytes: 0 }
  const descriptors: number[] = []
  let interrupt: NodeJS.Signals | null = null, launchError: string | null = null, captureError: string | null = null
  let code: number | null = null, signal: NodeJS.Signals | null = null
  try {
    const out = openSync(join(directory, "stdout.log"), "wx", 0o600); descriptors.push(out)
    const err = openSync(join(directory, "stderr.log"), "wx", 0o600); descriptors.push(err)
    const child = spawn(argv[0]!, argv.slice(1), { cwd, stdio: ["ignore", "pipe", "pipe"] })
    const forward = (received: NodeJS.Signals) => { interrupt ??= received; child.kill(received) }
    const onInt = () => forward("SIGINT"), onTerm = () => forward("SIGTERM")
    process.on("SIGINT", onInt); process.on("SIGTERM", onTerm)
    const retain = (fd: number, observed: typeof stdout, bytes: Buffer) => {
      if (captureError) return
      try {
        let offset = 0
        while (offset < bytes.length) {
          const written = writeSync(fd, bytes, offset)
          if (written <= 0) throw new Error("capture write made no progress")
          observed.hash.update(bytes.subarray(offset, offset + written)); observed.bytes += written
          offset += written
        }
      }
      catch (error) { captureError = String(error); child.kill("SIGTERM") }
    }
    try {
      child.stdout.on("data", (bytes: Buffer) => retain(out, stdout, bytes))
      child.stderr.on("data", (bytes: Buffer) => retain(err, stderr, bytes))
      child.on("error", (error) => { launchError = String(error) })
      await new Promise<void>((done) => child.on("close", (exitCode, exitSignal) => { code = exitCode; signal = exitSignal; done() }))
    } finally { process.off("SIGINT", onInt); process.off("SIGTERM", onTerm) }
  } finally { for (const fd of descriptors) closeSync(fd) }
  const receipt: Receipt = {
    schema: 1, id: start.id, endedAt: new Date().toISOString(),
    termination: captureError ? "capture-failed" : launchError ? "launch-failed" : interrupt ? "interrupted" : signal ? "signalled" : "exited",
    exitCode: code, signal, interrupt, error: captureError ?? launchError,
    start: startFact,
    stdout: { bytes: stdout.bytes, sha256: stdout.hash.digest("hex") },
    stderr: { bytes: stderr.bytes, sha256: stderr.hash.digest("hex") },
  }
  save(join(directory, "receipt.json"), receipt)
  const verified = inspect(directory)
  if (!verified.receipt) throw new Error(`incomplete fresh capture: ${directory}`)
  console.log(JSON.stringify({ directory, ...verified, stdout: join(directory, "stdout.log"), stderr: join(directory, "stderr.log") }, null, 2))
  return verified.receipt.termination === "exited" ? verified.receipt.exitCode ?? 1 : 1
}

export async function main(args: readonly string[]): Promise<number> {
  try {
    if (!args.length || args[0] === "--help" || args[0] === "help" || args.length === 2 && ["run", "inspect"].includes(args[0]!) && args[1] === "--help") { console.log(HELP); return 0 }
    if (args[0] === "run") return await run(args.slice(1))
    if (args[0] === "inspect" && args.length === 2) {
      const directory = resolve(args[1]!), result = inspect(directory)
      console.log(JSON.stringify({ directory, ...result, stdout: join(directory, "stdout.log"), stderr: join(directory, "stderr.log"), ...(!result.receipt ? { limit: "Incomplete capture: no closing receipt. Partial output does not establish completion." } : {}) }, null, 2))
      return result.receipt ? 0 : 1
    }
    throw new Error("unknown command or options; see --help")
  } catch (error) { console.error(`evidence: ${error instanceof Error ? error.message : String(error)}`); return 1 }
}
